name: ScoreboardAPI
main: jasonwynn10\ScoreboardAPI\ScoreboardAPI
version: 1.1.0
api: [ "4.0.0" ]
php: "7.4"
author: "jasonwynn10"
description: "A simple API for creating scoreboards on PocketMine-MP servers"
load: STARTUP